name: mongo_sales_stack

services:
  mongo_sales:
    image: mongo:7
    container_name: mongo_sales
    env_file:
      - ../../../../.env.local
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS:-YourStrong@Passw0rd1}"
      MONGO_INITDB_DATABASE: "tiendaDB"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_sales_data:/data/db
    networks:
      - sales_net
    healthcheck:
      test: ["CMD", "mongosh", "-u", "${MONGO_USER:-root}", "-p", "${MONGO_PASS:-YourStrong@Passw0rd1}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 30

  init_mongo_sales:
    image: mongo:7
    container_name: mongo_sales_init
    depends_on:
      mongo_sales:
        condition: service_healthy
    env_file:
      - ../../../../.env.local
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS:-YourStrong@Passw0rd1}"
      MONGO_HOST: "mongo_sales"
      MONGO_DB: "tiendaDB"
    volumes:
      - ./init:/scripts
      - ../../../../data/out:/seed_data:ro
    networks:
      - sales_net
    profiles:
      - init
    entrypoint:
      - /bin/bash
      - -lc
      - |
        find /scripts -type f -name '*.sh' -exec sed -i 's/\r$//' {} +
        bash /scripts/run-init.sh

volumes:
  mongo_sales_data:
    name: mongo_sales_data

networks:
  sales_net:
    name: sales_net
    driver: bridge
    external: true
